/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mav.buildscale.plugin;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;

import static org.junit.jupiter.api.Assertions.assertTrue;

class BuildscalePluginFunctionalTest {

    @Test
    void verbose_report() throws IOException {
        // arrange
        final File projectDir = new File("build/functionalTest");
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        writeString(new File(projectDir, "build.gradle"),
                """
                        plugins {
                            id('com.mav.buildscale')
                        }
                                            
                        buildscale {
                            publishEnabled = false
                            verboseEnabled = true
                        }""");

        // act
        final GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withProjectDir(projectDir);
        final BuildResult result = runner.build();

        // assert
        assertTrue(result.getOutput().contains("Build report:"));
    }

    private void writeString(final File file, final String string) throws IOException {
        try (final Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
