server:
  port: 8002

spring:
  jpa:
    open-in-view: false
  liquibase:
    enabled: true
    change-log: /db/changelog/main.xml

logging:
  config: classpath:logback-spring.xml
  level:
    com.mav.buildscale: debug